# Change these first
owner: cristdulcey # Your GitHub organization or username, where this repository lives
repo: upptime-loducode # The name of this repository

assignees:
  - cristdulcey

sites:
  - name: Loducode
    url: https://loducode.com/
  - name: AXA
    url: https://axacolpatriabot.com/69b16986-ff63-11ea-adc1-0242ac120002/
  - name: Pasmo dev
    url: https://app.holaubi.org/
  - name: Pasmo pro
    url: https://chatbot.holaubi.org/
  - name: KOZ lands Dev
    url: https://kingdom-of-zoe.loducode.com/es/lands/
  - name: KOZ lands Prodution
    url: https://sale.kingdomofzoe.app/es/lands/
  - name: Mi pasaje
    url: https://mi-pasaje.loducode.com/
  - name: Tipsco
    url: https://tipsco.com/es/products/
    __dangerous__disable_verify_peer: true
    __dangerous__disable_verify_host: true
  - name: Tipsco dev
    url: http://3.145.1.238:30003/es/
  - name: Vault loducode
    url: https://vault.loducode.com/ui/vault/auth/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-loducode
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Pagina de estado de las pagina que administra de *loducode sas*"
  introMessage: Aqui se motraran la pagina del bot de axa, Loducode, pasmo, Kingdom of zoe, Mi pasaje, Tipsco, Tipsco dev, Vault
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
